#!/usr/bin/env bash

read -rd '' block <<'EOS' ||:
  IFS=$'\n' read -rd '' -a statements <<'  EOS' ||:
    RETVAL=$?
    [[ -z $__ || -z ${__heap[$__]} ]] && IRBSH='' || IRBSH="[$RETVAL]=> ${__heap[$__]}"
    __=''
  EOS
  PROMPT_COMMAND=$(IFS=';'; echo "${statements[*]}")
  unset -v statements
  PS1="\$IRBSH\${IRBSH:+\\n}irbsh-11.10> "
  source %s/rubsh
  __strict_mode off
EOS
printf -v block "$block" "$(dirname "$(readlink -f "$BASH_SOURCE")")"

exec bash --rcfile <(echo "$block")
