#!/usr/bin/env bash

read -rd '' block <<'EOS' ||:
  IFS=$'\n' read -rd '' -a statements <<'  EOS' ||:
    RETVAL=$?
    [[ -z $__ ]] && IRBSH='' || IRBSH="[$RETVAL]=> $__"
    __=''
  EOS
  PROMPT_COMMAND=$(IFS=';'; echo "${statements[*]}")
  unset -v statements
  PS1="\$IRBSH\${IRBSH:+\\n}irbsh-\$RUBSH_VERSION> "
  source %s/rubsh
  strict_mode off
EOS
printf -v block "$block" "$(dirname "$(readlink -f "$BASH_SOURCE")")"

exec bash --rcfile <(echo "$block")
