#!/usr/bin/env bash

rubsh_lib () { (
  unset -v CDPATH
  cd "$(dirname "$(readlink "$BASH_SOURCE" || echo "$BASH_SOURCE")")" && pwd -P
) }

export RUBSH_LIB=$(rubsh_lib)
export RUBSH_PATH+=${RUBSH_PATH:+:}$RUBSH_LIB:.
source "$RUBSH_LIB"/keywords.rubsh

require utils
rubsh_initialize

require object
require class
require string
require array
require hash
require file

rubsh_cleanup

$(return_if_sourced)

bash --norc
