#!/usr/bin/env bash

RUBSH_LIB=$(dirname "$(readlink -f "$BASH_SOURCE")")
export RUBSH_PATH=$RUBSH_LIB${RUBSH_PATH:+:}${RUBSH_PATH:-}:.
source "$RUBSH_LIB"/keywords.rubsh
unset -v RUBSH_LIB

$(require util)

strict_mode on
glob off

# $(require object    )
# $(require class     )
# $(require string    )
# $(require array     )
# $(require hash      )
# $(require io        )
# $(require file      )

$(__return_if_sourced)

usage=''
(( $# )) || __die "$usage"
unset -v usage

source "$@"
